packages:
  - "apps/*"
  - "packages/*"
  - "packages/connectors/*"
  - "packages/ranking/*"
  - "packages/resolver/*"
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - esbuild
